default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>